import { IFunctionDetail, IModuleDetail, IModulesDetails } from '../models/account-status.model';
import { Roles } from '../models/system-roles';

export const DEFAULT_MODULE_VISIBLE_ROLES: Roles[] = [
    Roles.Developer,
    Roles.SystemAdministrator,
    Roles.EntityAdministrator,
    Roles.SystemUser,
];

export const MODULE_ROLE_VISIBILITY: Partial<Record<string, Roles[]>> = {
    ERPF: [Roles.Developer, Roles.SystemAdministrator],
    ERPM: [Roles.Developer, Roles.SystemAdministrator],
    SDB: [Roles.Developer, Roles.SystemAdministrator],
    SSM: [Roles.Developer, Roles.SystemAdministrator],
    SENT: [Roles.Developer, Roles.SystemAdministrator],
    SUA: [Roles.Developer, Roles.SystemAdministrator],
    SCP: [Roles.Developer, Roles.SystemAdministrator],
    ACT: [Roles.Developer, Roles.SystemAdministrator, Roles.EntityAdministrator, Roles.SystemUser, Roles.Guest],
    NOT: [Roles.Developer, Roles.SystemAdministrator, Roles.EntityAdministrator, Roles.SystemUser, Roles.Guest],
    PRF: [Roles.Developer, Roles.SystemAdministrator, Roles.EntityAdministrator, Roles.SystemUser, Roles.Guest],
    SET: [Roles.Developer, Roles.SystemAdministrator, Roles.EntityAdministrator, Roles.SystemUser, Roles.Guest],
    LGOT: [Roles.Developer, Roles.SystemAdministrator, Roles.EntityAdministrator, Roles.SystemUser, Roles.Guest],
};

export const STATIC_FUNCTIONS_DETAILS: Record<string, IFunctionDetail> = {
    Summary: {
        FunctionID: 1,
        Name: 'Summary',
        Name_Regional: 'الملخص',
        Default_Order: 1,
        URL: '/summary',
    },
    SysAdm: {
        FunctionID: 2,
        Name: 'System Administration',
        Name_Regional: 'إدارة النظام',
        Default_Order: 2,
        URL: '/system-administration',
    },
    EntAdm: {
        FunctionID: 3,
        Name: 'Entity Administration',
        Name_Regional: 'إدارة المنشأة',
        Default_Order: 3,
        URL: '/entity-administration',
    },
    DC: {
        FunctionID: 4,
        Name: 'Document Control',
        Name_Regional: 'التحكم في المستندات',
        Default_Order: 4,
        URL: '/document-control',
    },
    FIN: {
        FunctionID: 5,
        Name: 'Finance & Accounting',
        Name_Regional: 'المالية والمحاسبة',
        Default_Order: 5,
        URL: '/financials',
    },
};

export const STATIC_MODULES_DETAILS: IModulesDetails = {
    ACT: {
        ModuleID: 1,
        FunctionID: 1,
        Name: 'Actions',
        Name_Regional: 'الإجراءات',
        Default_Order: 1,
        URL: '/summary/actions',
    },
    NOT: {
        ModuleID: 2,
        FunctionID: 1,
        Name: 'Notifications',
        Name_Regional: 'الإشعارات',
        Default_Order: 2,
        URL: '/summary/notifications',
    },
    PRF: {
        ModuleID: 3,
        FunctionID: 1,
        Name: 'Profile',
        Name_Regional: 'الملف الشخصي',
        Default_Order: 3,
        URL: '/summary/profile',
    },
    SET: {
        ModuleID: 4,
        FunctionID: 1,
        Name: 'Settings',
        Name_Regional: 'الإعدادات',
        Default_Order: 4,
        URL: '/summary/settings',
    },
    LGOT: {
        ModuleID: 5,
        FunctionID: 1,
        Name: 'Logout',
        Name_Regional: 'تسجيل الخروج',
        Default_Order: 5,
        URL: '',
    },
    SDB: {
        ModuleID: 6,
        FunctionID: 2,
        Name: 'System Dashboard',
        Name_Regional: 'لوحة تحكم النظام',
        Default_Order: 1,
        URL: '/system-administration',
    },
    ERPF: {
        ModuleID: 7,
        FunctionID: 2,
        Name: 'ERP Functions',
        Name_Regional: 'وظائف النظام',
        Default_Order: 2,
        URL: '/system-administration/erp-functions',
    },
    ERPM: {
        ModuleID: 8,
        FunctionID: 2,
        Name: 'ERP Modules',
        Name_Regional: 'وحدات النظام',
        Default_Order: 3,
        URL: '/system-administration/erp-modules',
    },
    SCP: {
        ModuleID: 9,
        FunctionID: 2,
        Name: 'System Control Panel',
        Name_Regional: 'لوحة تحكم النظام',
        Default_Order: 4,
        URL: '',
    },
    SSM: {
        ModuleID: 90,
        FunctionID: 2,
        Name: 'System Storage Management',
        Name_Regional: 'إدارة تخزين النظام',
        Default_Order: 5,
        URL: '/system-administration/system-storage-management',
    },
    SENT: {
        ModuleID: 91,
        FunctionID: 2,
        Name: 'System Entities',
        Name_Regional: 'كيانات النظام',
        Default_Order: 6,
        URL: '/system-administration/system-entities',
    },
    SUA: {
        ModuleID: 92,
        FunctionID: 2,
        Name: 'System User Accounts',
        Name_Regional: 'حسابات مستخدمي النظام',
        Default_Order: 7,
        URL: '/system-administration/user-accounts',
    },
    ENTDT: {
        ModuleID: 10,
        FunctionID: 3,
        Name: 'Entities',
        Name_Regional: 'المنشآت',
        Default_Order: 1,
        URL: '/entity-administration/entities',
    },
    USRACC: {
        ModuleID: 11,
        FunctionID: 3,
        Name: 'User Accounts',
        Name_Regional: 'حسابات المستخدمين',
        Default_Order: 2,
        URL: '/entity-administration/entity-user-accounts',
    },
    WF: {
        ModuleID: 12,
        FunctionID: 3,
        Name: 'Workflows',
        Name_Regional: 'سير العمل',
        Default_Order: 3,
        URL: '/entity-administration/workflows',
    },
    ROLES: {
        ModuleID: 13,
        FunctionID: 3,
        Name: 'Roles',
        Name_Regional: 'الأدوار',
        Default_Order: 4,
        URL: '/entity-administration/roles',
    },
    EACC: {
        ModuleID: 14,
        FunctionID: 3,
        Name: 'Entity Accounts',
        Name_Regional: 'حسابات المنشأة',
        Default_Order: 5,
        URL: '',
    },
    ESM: {
        ModuleID: 93,
        FunctionID: 3,
        Name: 'Entity Storage Management',
        Name_Regional: 'إدارة تخزين المنشأة',
        Default_Order: 6,
        URL: '/entity-administration/entity-storage-management',
    },
    GP: {
        ModuleID: 94,
        FunctionID: 3,
        Name: 'Groups',
        Name_Regional: 'المجموعات',
        Default_Order: 7,
        URL: '/entity-administration/entity-groups',
    },
    SHDOC: {
        ModuleID: 15,
        FunctionID: 4,
        Name: 'Shared Documents',
        Name_Regional: 'المستندات المشتركة',
        Default_Order: 1,
        URL: '/document-control',
    },
    CINV: {
        ModuleID: 16,
        FunctionID: 5,
        Name: 'Invoices',
        Name_Regional: 'الفواتير',
        Default_Order: 1,
        URL: '/financials',
    },
};
